config/routes.rb
require 'sidekiq/web'

Iso::Application.routes.draw do
  devise_for :admin_users

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope path: "(:locale)", shallow_path: "(:locale)" do
    resources :photographs, only: [:index, :show] do
      collection do
        get :explore
        get :recommended
        get :search, to: redirect("/%{locale}/photographs")
        get :random
        get :favourites
        get :following
        get :seeking_feedback
      end

      member do
        post :recommend
        get :share
      end

      resources :favourites, only: [:create, :destroy]
      resources :reports, only: [:new, :create]
    end

    resources :comment_threads do
      resources :comments, only: [:create, :update, :destroy] do
        member do
          get :toggle
        end
      end
    end

    resources :collections, only: [:index, :show] do
      collection do
        get :explore
      end

      resources :reports, only: [:new, :create]
    end

    resources :categories, only: [:show] do
      resources :photographs, only: [:index]
      resources :collections, only: [:index]
    end

    resources :licenses, only: [:show] do
      resources :photographs, only: [:index]
    end

    resources :notifications, only: [:index, :show] do
      collection do
        get :mark_all_as_read
      end
    end

    resources :users, shallow: true, only: [:show] do
      resources :collections, only: [:index, :show] do
        resources :photographs, only: [:index]
      end

      resources :followings, only: [:create, :destroy]
      resources :photographs, only: [:index]
    end

    devise_for :users, path: :account, controllers: { 
      registrations: "devise_extensions/registrations",
      invitations: "devise_extensions/invitations"
    }

    namespace :account do
      resources :photographs do
        collection do
          get :public
          get :private
          get :unsorted
          post :mass_update
          get :typeahead
        end
      end

      resources :collections, shallow: true do
        resources :photographs do
          collection do
            post :mass_update
          end
        end
      end

      resources :authorisations, only: [:index]

      root to: "account#dashboard"
    end

    resources :reports, only: [:new, :create]

    get "/p/:id" => "photographs#share", as: :short_photo
    get "/u/:id" => "users#show", as: :short_user
    get "/c/:id" => "collections#show", as: :short_collection
    get "/status" => "pages#up", as: :status
    get "/stats" => "pages#stats", as: :stats
    get "/sitemap" => "pages#sitemap", as: :sitemap
    get "/about" => "pages#about", as: :about
    get "/terms" => "pages#terms", as: :terms
  end

  get "/auth/:provider/callback" => "account/authorisations#create"

  # Handle root locale path
  get "/:locale" => "pages#home", as: :home
  root to: "pages#home"
end

app/views/shared/_account_nav.html.slim
nav id="account-nav" class="panel"
  header
    h5= t("account.nav.title")
  ul class="side-nav"
    = link_to t("account.nav.home"), account_root_path, active_on: true, \
      active_wrapper: :li
    = link_to t("account.nav.settings"), edit_user_registration_path, active_on: true, \
      active_wrapper: :li
    = link_to t("account.nav.invite"), new_user_invitation_path, active_on: true, \
      active_wrapper: :li
    = link_to t("account.nav.photographs"), account_photographs_path, \
      active_on: /\/account(.*)\/photographs/i, active_wrapper: :li

  div class="upload-quota"
    h6= t("account.nav.upload_quota")
    div class="progress"
      span class="meter" style="width: #{current_user.percentage_of_upload_quota_used_this_month}%;"

    span class="used"
      = current_user.upload_count_for_this_month
    span class="quota"
      = current_user.upload_quota

    div class="clear"
    span class="more"
      = t("account.nav.get_more_uploads", path: new_user_invitation_path).html_safe

nav id="photographs-nav" class="panel"
  header
    h5= t("account.photographs.nav.title")

  ul class="side-nav"
    = link_to t("account.photographs.nav.all"), account_photographs_path, \
      active_on: true, active_wrapper: :li

    = link_to t("account.photographs.nav.unsorted"), unsorted_account_photographs_path, \
      active_on: true, active_wrapper: :li

  h6= t("account.photographs.nav.collections")
  ul class="side-nav"
    - current_user.collections.order("name").each do |collection|
      = link_to collection.name, account_collection_photographs_path(collection), \
        active_on: true, active_wrapper: :li

    button data-reveal-id="new-collection-modal" class="small expand new-collection"
      = t("account.collections.modal.new.button")

app/views/shared/_analytics.html.slim
- if Rails.env.production?
  - if ENV['GAUGES_SITE_ID'].present?
    javascript:
      var _gauges = _gauges || [];
      (function() {
        var t   = document.createElement('script');
        t.type  = 'text/javascript';
        t.async = true;
        t.id    = 'gauges-tracker';
        t.setAttribute('data-site-id', '#{ENV['GAUGES_SITE_ID']}');
        t.src = '//secure.gaug.es/track.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(t, s);
      })();

  - if ENV['GOOGLE_ANALYTICS_ID'].present?
    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '#{ENV['GOOGLE_ANALYTICS_ID']}', 'photographer.io');
      ga('send', 'pageview');

app/views/shared/_anon_nav.html.slim
nav id="layout-nav" class="top-bar"
  ul class="title-area"
    li class="name"
      h1 id="logo"
        = link_to t("site_name"), home_path

    li class="toggle-topbar menu-icon"
      = link_to "#" do
        span= t("nav.menu")

  section class="top-bar-section"
    ul class="left"
      - cache([I18n.locale, :nav, :explore, current_user, request.fullpath], expires_in: 10.minutes) do
        li class="has-dropdown"
          = link_to t("nav.explore"), explore_collections_path, active_on: /\/explore/i
          ul class="dropdown explore-menu"
            li
              div class="row"
                div class="large-12 columns"
                  label= t("nav.general")
                  ul class="sub-nav"
                    li
                      = link_to t("nav.random"), random_photographs_path, title: t("nav.random")
                    = link_to t("nav.latest"), explore_collections_path, active_on: true, \
                      active_wrapper: :li
                    
                    - if user_signed_in?
                      = link_to t("nav.following"), following_photographs_path, \
                        active_on: true, active_wrapper: :li
                    
                    = link_to t("nav.seeking_feedback"), seeking_feedback_photographs_path, active_on: true, active_wrapper: :li

              div class="row"
                div class="large-12 columns"
                  label= t("nav.categories")
    
              div class="row"
                - @categories.each_slice((@categories.size / 2) + 1) do |categories|
                  div class="large-6 columns"
                    ul class="sub-nav"
                      - categories.each do |category|
                        = link_to category.name, category_path(category.slug), active_on: category_photographs_path(category.slug), \
                          active_wrapper: :li

      = link_to t("nav.recommended"), recommended_photographs_path, active_on: true, \
        active_wrapper: :li

      li= link_to t("nav.blog"), blog_path
      li= link_to t("nav.support"), "mailto:#{ISO[:support_email]}"

    ul class="right"
      = link_to t("nav.sign_in"), new_user_session_path, active_on: true, \
        active_wrapper: :li

      li class="has-form"
        = link_to t("nav.sign_up"), new_user_registration_path, active_on: true, \
          class: "button tiny success"

app/views/shared/_filter_subnav.html.slim
dl class="sub-nav"
  dt= t("photographs.sub_nav.filter")
  = link_to t("photographs.sub_nav.grouped"), switch_filter_path(:photographs, :collections), \
    active_on: /\/collections/i, active_wrapper: :dd
  = link_to t("photographs.sub_nav.all"), switch_filter_path(:collections, :photographs), \
    active_on: /\/photographs/i, active_wrapper: :dd

app/views/shared/_nav.html.slim
nav id="layout-nav" class="top-bar"
  ul class="title-area"
    li class="name"
      h1 id="logo"
        = link_to t("site_name"), home_path

    li class="toggle-topbar menu-icon"
      = link_to "#" do
        span= t("nav.menu")

  section class="top-bar-section"
    ul class="left"
      - cache([I18n.locale, :nav, :explore, current_user, request.fullpath], expires_in: 10.minutes) do
        li class="has-dropdown"
          = link_to t("nav.explore"), explore_collections_path, active_on: /\/explore/i
          ul class="dropdown explore-menu"
            li
              div class="row"
                div class="large-12 columns"
                  label= t("nav.general")
                  ul class="sub-nav"
                    li
                      = link_to t("nav.random"), random_photographs_path, title: t("nav.random")
                    = link_to t("nav.latest"), explore_collections_path, active_on: true, \
                      active_wrapper: :li
                    
                    - if user_signed_in?
                      = link_to t("nav.following"), following_photographs_path, \
                        active_on: true, active_wrapper: :li
                    
                    = link_to t("nav.seeking_feedback"), seeking_feedback_photographs_path, active_on: true, active_wrapper: :li

              div class="row"
                div class="large-12 columns"
                  label= t("nav.categories")
    
              div class="row"
                - @categories.each_slice((@categories.size / 2) + 1) do |categories|
                  div class="large-6 columns"
                    ul class="sub-nav"
                      - categories.each do |category|
                        = link_to category.name, category_path(category.slug), active_on: category_photographs_path(category.slug), \
                          active_wrapper: :li

              - if @licenses.present?
                div class="row"
                  div class="large-12 columns"
                    label= t("nav.license")

                div class="row"
                  - @licenses.each_slice((@licenses.size / 2) + 1) do |licenses|
                    div class="large-6 columns"
                      ul class="sub-nav"
                        - licenses.each do |license|
                          = link_to license.code, license_path(license), active_on: license_photographs_path(license), \
                            active_wrapper: :li

      = link_to t("nav.recommended"), recommended_photographs_path, active_on: true, \
        active_wrapper: :li

      li= link_to t("nav.blog"), blog_path
      li= link_to t("nav.support"), "mailto:#{ISO[:support_email]}"

    ul class="right"
      - if user_signed_in?
        li id="mini-user-stats" class="has-form"
          = link_to account_root_path do
            span class="views" title=(t("nav.mini_stats.views"))
              span class="icon"
              span class="number"
                = current_user.photograph_views.to_i

            span class="followers" title=(t("nav.mini_stats.followers"))
              span class="icon"
              span class="number"
                = current_user.followers_count.to_i

            span class="recommendations" title=(t("nav.mini_stats.recommendations"))
              span class="icon"
              span class="number"
                = current_user.received_recommendations_count.to_i

            span class="favourites" title=(t("nav.mini_stats.favourites"))
              span class="icon"
              span class="number"
                = current_user.received_favourites_count.to_i
            
        li class="has-dropdown"
          = link_to current_user.name, account_root_path, active_on: true
          ul class="dropdown"
            = link_to t("nav.dashboard"), account_root_path, active_on: true, \
              active_wrapper: :li

            = link_to t("nav.edit_account"), edit_user_registration_path, \
              active_on: true, active_wrapper: :li

            = link_to t("nav.profile"), short_user_path(current_user.username), active_on: true, \
              active_wrapper: :li

            = link_to t("nav.photographs"), account_photographs_path, active_on: true, \
              active_wrapper: :li

            = link_to t("nav.favourites"), favourites_photographs_path, active_on: true, \
              active_wrapper: :li

            li= link_to t("nav.sign_out"), destroy_user_session_path, method: :delete

        li id="notifications"
          - unread = current_user.notifications.unread.count > 0
          a class="#{unread ? 'unread' : 'read'}" data-dropdown="notifications-dropdown" href="#"
      
      - else
        = link_to t("nav.sign_in"), new_user_session_path, active_on: true, \
          active_wrapper: :li

        li class="has-form"
          = link_to t("nav.sign_up"), new_user_registration_path, active_on: true, \
            class: "button tiny success"

- content_for(:after_body) do
  - if user_signed_in?
    div[id="notifications-dropdown" class="f-dropdown small" data-dropdown-content]
      header
        h5= t("notifications.title")

      - if current_user.notifications.unread.count > 0
        div class="notifications"
          - current_user.notifications.unread.order("created_at DESC").each do |n|
            div class="notification"
              = link_to n.subject, notification_path(n), class: (n.read? ? "read" : "unread")
        footer
          = link_to t("notifications.mark_as_read"), mark_all_as_read_notifications_path

      - else
        span class="none"
          = t("notifications.none")

app/views/shared/_pingdom.html.slim
- if Rails.env.production?
  - if ENV['PINGDOM_SITE_ID'].present?
    javascript:
      var _prum = [['id', '#{ENV['PINGDOM_SITE_ID']}'],
                   ['mark', 'firstbyte', (new Date()).getTime()]];
      (function() {
          var s = document.getElementsByTagName('script')[0]
            , p = document.createElement('script');
          p.async = 'async';
          p.src = '//rum-static.pingdom.net/prum.min.js';
          s.parentNode.insertBefore(p, s);
      })();

app/views/shared/_pubnub.html.slim
- if user_signed_in? && $pubnub.present? && $pubnub.subscribe_key.present?
  = javascript_include_tag "https://pubnub.a.ssl.fastly.net/pubnub-3.5.0.min.js"

  javascript:
    var pubnub = PUBNUB.init({ 
      subscribe_key: '#{$pubnub.subscribe_key}',
      ssl: true
    });

    function receive(message, envelope, source_channel) {
      pubnub.events.fire(message.type, message);
    }

    pubnub.subscribe({
      channel: '#{current_user.channel_key}',
      callback: receive 
    });

app/views/shared/_social_buttons.html.slim
- url = URI::escape(request.original_url)
div class="social-buttons"
  a class="g-plus button tiny expand radius" href="https://plus.google.com/share?url=#{url}" data-action="share" data-width="500" data-height="400"
    = t("social.google_plus")

  a class="fb-share button tiny expand radius" href="https://www.facebook.com/sharer/sharer.php?u=#{url}" data-action="share" data-width="626" data-height="436"
    = t("social.facebook")

  a class="twitter-share button tiny expand radius" href="https://twitter.com/intent/tweet?url=#{url}&via=#{t('social.twitter_account').gsub('@', '')}" data-action="share" data-width="550" data-height="420"
    = t("social.twitter")

- content_for(:javascript) do
  javascript:
    $("body").on("click", "[data-action = 'share']", function(e) {
      e.preventDefault();
      var url = $(this).attr("href");
      var width = $(this).data("width");
      var height = $(this).data("height");
      var sizeString = "width=" + width + ",height=" + height;
      window.open(url, 'sharer', sizeString);
    });