config/routes.rb
require 'sidekiq/web'

Iso::Application.routes.draw do
  devise_for :admin_users

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope path: "(:locale)", shallow_path: "(:locale)" do
    resources :photographs, only: [:index, :show] do
      collection do
        get :explore
        get :recommended
        get :search, to: redirect("/%{locale}/photographs")
        get :random
        get :favourites
        get :following
        get :seeking_feedback
      end

      member do
        post :recommend
        get :share
      end

      resources :favourites, only: [:create, :destroy]
      resources :reports, only: [:new, :create]
    end

    resources :comment_threads do
      resources :comments, only: [:create, :update, :destroy] do
        member do
          get :toggle
        end
      end
    end

    resources :collections, only: [:index, :show] do
      collection do
        get :explore
      end

      resources :reports, only: [:new, :create]
    end

    resources :categories, only: [:show] do
      resources :photographs, only: [:index]
      resources :collections, only: [:index]
    end

    resources :licenses, only: [:show] do
      resources :photographs, only: [:index]
    end

    resources :notifications, only: [:index, :show] do
      collection do
        get :mark_all_as_read
      end
    end

    resources :users, shallow: true, only: [:show] do
      resources :collections, only: [:index, :show] do
        resources :photographs, only: [:index]
      end

      resources :followings, only: [:create, :destroy]
      resources :photographs, only: [:index]
    end

    devise_for :users, path: :account, controllers: { 
      registrations: "devise_extensions/registrations",
      invitations: "devise_extensions/invitations"
    }

    namespace :account do
      resources :photographs do
        collection do
          get :public
          get :private
          get :unsorted
          post :mass_update
          get :typeahead
        end
      end

      resources :collections, shallow: true do
        resources :photographs do
          collection do
            post :mass_update
          end
        end
      end

      resources :authorisations, only: [:index]

      root to: "account#dashboard"
    end

    resources :reports, only: [:new, :create]

    get "/p/:id" => "photographs#share", as: :short_photo
    get "/u/:id" => "users#show", as: :short_user
    get "/c/:id" => "collections#show", as: :short_collection
    get "/status" => "pages#up", as: :status
    get "/stats" => "pages#stats", as: :stats
    get "/sitemap" => "pages#sitemap", as: :sitemap
    get "/about" => "pages#about", as: :about
    get "/terms" => "pages#terms", as: :terms
  end

  get "/auth/:provider/callback" => "account/authorisations#create"

  # Handle root locale path
  get "/:locale" => "pages#home", as: :home
  root to: "pages#home"
end

app/views/pages/about.html.slim
- cache([I18n.locale, :about], expires_in: 10.minutes) do
  section id="pages-about"
    header class="row"
      div class="large-12 columns"
        h1= t("about.title")

    div class="row"
      section class="points small-12 large-8 large-offset-2 columns"
        header
          h2= t("about.subtitle")

        article
          h3= t("about.free.title")
          = simple_format t("about.free.body")

        article
          h3= t("about.open_source.title")
          = simple_format t("about.open_source.body")

        article
          h3= t("about.advertising.title")
          = simple_format t("about.advertising.body")

        article
          h3= t("about.money.title")
          = simple_format t("about.money.body")

        article
          h3= t("about.likes.title")
          = simple_format t("about.likes.body", quota: ISO[:defaults][:recommendation_quota])
        article
          h3= t("about.comments.title")
          = simple_format t("about.comments.body")

        article
          h3= t("about.privacy.title")
          = simple_format t("about.privacy.body")

        article
          h3= t("about.compare.title")

          table
            thead
              tr
                th
                th= t("about.compare.flickr.title")
                th= t("about.compare.500px.title")
                th= t("about.compare.photographerio.title")
            tbody
              thead
                tr
                  th colspan="4"
                    = t("about.compare.free_accounts")
              tr
                th= t("about.compare.uploads")
                td= t("about.compare.flickr.uploads")
                td= t("about.compare.500px.uploads")
                td= t("about.compare.photographerio.uploads")

              tr
                th= t("about.compare.albums")
                td= t("about.compare.flickr.albums")
                td= t("about.compare.500px.albums")
                td= t("about.compare.photographerio.albums")

              tr
                th= t("about.compare.advertising")
                td= t("about.compare.flickr.advertising")
                td= t("about.compare.500px.advertising")
                td= t("about.compare.photographerio.advertising")

              thead
                tr
                  th colspan="4"
                    = t("about.compare.else")
              tr
                th= t("about.compare.ssl")
                td= t("about.compare.flickr.ssl")
                td= t("about.compare.500px.ssl")
                td= t("about.compare.photographerio.ssl")
                
          aside class="notes"
            = simple_format t("about.compare.notes")

        article class="sign-up"
          header
            h3= t("about.interested")

          div class="button-container"
            = link_to t("about.sign_up"), new_user_registration_path, class: "button success large radius"

app/views/pages/home.html.slim
- content_for(:body_class, "darkroom")

section id="pages-home"
  article id="hero-photograph"
    - if @photograph.present?
      = link_to photograph_path(@photograph) do
        - if @photograph.has_precalculated_sizes?
          = photo_tag @photograph, :homepage
        - else
          - if photo.landscape?
            = photo_tag @photograph, "2000x", quality: 80
          - else
            = photo_tag @photograph, "2000x1400#", quality: 80
    
      div id="hero-blurb"
        header
          h2= t("home.title")
          h4= simple_format t("home.blurb", \
            name: link_to(@photograph.user.name, short_user_path(@photograph.user.username)), image_path: photograph_path(@photograph),
            word: t("home.words").sample)

          - unless user_signed_in?
            div class="buttons"
              = link_to t("home.about"), about_path, class: "button small"

              span class="or"
                = t("home.or")

              = link_to t("home.sign_up"), new_user_registration_path, class: "button success small"

app/views/pages/sitemap.xml.slim
- cache(:sitemap, expires_in: 15.minutes) do
  - base_url = "https://www.photographer.io"
  doctype xml

  urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
    url
      loc== base_url
      lastmod= w3c_date(Time.now)
      changefreq= "always"

    url
      loc== [base_url, explore_photographs_path].join
      lastmod= w3c_date(@photographs.last.updated_at)
      changefreq= "always"

    url
      loc== [base_url, recommended_photographs_path].join
      lastmod= w3c_date(Time.now)
      changefreq= "always"

    - @photographs.find_each do |photo|
      url
        loc== [base_url, photograph_path(photo)].join
        lastmod= w3c_date(photo.updated_at)
        changefreq= "hourly"
        priority= "1"

    url
      loc== [base_url, explore_collections_path].join
      lastmod= w3c_date(@collections.last.updated_at)
      changefreq= "always"

    - @collections.find_each do |collection|
      url
        loc== [base_url, collection_path(collection)].join
        lastmod= w3c_date(collection.updated_at)
        changefreq= "daily"
        priority= "1"

    - cache([:sitemap, :categories], expires_in: 1.day) do
      - @categories.each do |category|
        url
          loc== [base_url, category_path(category.slug)].join
          lastmod= w3c_date(Time.now)
          changefreq= "daily"
          priority="1"

app/views/pages/terms.html.slim
section id="pages-terms"
  div class="row"
    div class="small-12 large-8 large-offset-2 columns"
      article id="terms"
        == @terms_html