config/routes.rb
require 'sidekiq/web'

Iso::Application.routes.draw do
  devise_for :admin_users

  authenticate :admin_user do
    mount Sidekiq::Web => '/sidekiq'
  end

  scope path: "(:locale)", shallow_path: "(:locale)" do
    resources :photographs, only: [:index, :show] do
      collection do
        get :explore
        get :recommended
        get :search, to: redirect("/%{locale}/photographs")
        get :random
        get :favourites
        get :following
        get :seeking_feedback
      end

      member do
        post :recommend
        get :share
      end

      resources :favourites, only: [:create, :destroy]
      resources :reports, only: [:new, :create]
    end

    resources :comment_threads do
      resources :comments, only: [:create, :update, :destroy] do
        member do
          get :toggle
        end
      end
    end

    resources :collections, only: [:index, :show] do
      collection do
        get :explore
      end

      resources :reports, only: [:new, :create]
    end

    resources :categories, only: [:show] do
      resources :photographs, only: [:index]
      resources :collections, only: [:index]
    end

    resources :licenses, only: [:show] do
      resources :photographs, only: [:index]
    end

    resources :notifications, only: [:index, :show] do
      collection do
        get :mark_all_as_read
      end
    end

    resources :users, shallow: true, only: [:show] do
      resources :collections, only: [:index, :show] do
        resources :photographs, only: [:index]
      end

      resources :followings, only: [:create, :destroy]
      resources :photographs, only: [:index]
    end

    devise_for :users, path: :account, controllers: { 
      registrations: "devise_extensions/registrations",
      invitations: "devise_extensions/invitations"
    }

    namespace :account do
      resources :photographs do
        collection do
          get :public
          get :private
          get :unsorted
          post :mass_update
          get :typeahead
        end
      end

      resources :collections, shallow: true do
        resources :photographs do
          collection do
            post :mass_update
          end
        end
      end

      resources :authorisations, only: [:index]

      root to: "account#dashboard"
    end

    resources :reports, only: [:new, :create]

    get "/p/:id" => "photographs#share", as: :short_photo
    get "/u/:id" => "users#show", as: :short_user
    get "/c/:id" => "collections#show", as: :short_collection
    get "/status" => "pages#up", as: :status
    get "/stats" => "pages#stats", as: :stats
    get "/sitemap" => "pages#sitemap", as: :sitemap
    get "/about" => "pages#about", as: :about
    get "/terms" => "pages#terms", as: :terms
  end

  get "/auth/:provider/callback" => "account/authorisations#create"

  # Handle root locale path
  get "/:locale" => "pages#home", as: :home
  root to: "pages#home"
end

app/controllers/account/photographs_controller.rb
module Account
  class PhotographsController < AccountController
    respond_to :html

    before_filter :set_parents
    def set_parents
      if params[:collection_id].present?
        @collection = current_user.collections.find(params[:collection_id])
        authorize! :manage, @collection
      end
    end

    def index
      if @collection.present?
        @photographs = @collection.photographs
      else
        @photographs = current_user.photographs
      end

      @photographs = @photographs.includes(:metadata).order("created_at DESC").page(params[:page])
      authorize! :manage, current_user.photographs.new
      respond_with @photographs
    end

    def public
      @photographs = current_user.photographs.visible.order("created_at desc").page(params[:page])
      authorize! :manage, current_user.photographs.new
      respond_with @photographs do |f|
        f.html { render :index }
      end
    end

    def private
      @photographs = current_user.photographs.private.order("created_at desc").page(params[:page])
      authorize! :manage, current_user.photographs.new
      respond_with @photographs do |f|
        f.html { render :index }
      end
    end

    def unsorted
      not_photographs = current_user.photographs.in_collections.pluck(:id)
      @photographs = current_user.photographs.not_in(not_photographs).order("created_at DESC").page(params[:page])
      authorize! :manage, current_user.photographs.new
      respond_with @photographs do |f|
        f.html { render :index }
      end
    end

    def new
      @photograph = current_user.photographs.new
      @photograph.build_comment_threads
      authorize! :create, @photograph
      respond_with @photograph
    end

    def create
      @photograph = Photograph.new_from_s3_upload(current_user, upload_params)

      authorize! :create, @photograph
      if @photograph.save
        if @collection.present?
          @photograph.collections << @collection
        end

        respond_with @photograph do |f|
          f.html do
            if request.xhr?
              render partial: "account/photographs/photograph", locals: { photograph: @photograph }  
            else
              redirect_to edit_account_photograph_path(@photograph)
            end
          end
          f.json { render json: @photograph.to_json }
        end
      else
        respond_with @photograph, status: :bad_request do |f|
          f.html do
            if request.xhr?
              render text: t("account.photographs.create.failed")
            else
              render :new
            end
          end
          f.json { render text: t("account.photographs.create.failed") }
        end
      end
    end

    def show
      @photograph = current_user.photographs.find(params[:id])
      authorize! :update, @photograph
      respond_with @photograph do |f|
        f.html { redirect_to edit_account_photograph_path(@photograph) }
      end
    end

    def edit
      @photograph = current_user.photographs.find(params[:id])
      @photograph.build_comment_threads
      authorize! :update, @photograph
      respond_with @photograph
    end

    def update
      benchmark "Fetching and authorizing record" do
        @photograph = current_user.photographs.find(params[:id])
        authorize! :update, @photograph
      end

      benchmark "Updating records" do
        if @photograph.update_attributes(photograph_params)
          flash[:notice] = t("account.photographs.update.succeeded")
          respond_with @photograph do |f|
            f.html { redirect_to edit_account_photograph_path(@photograph) }
          end
        else
          flash.now[:alert] = t("account.photographs.update.failed")
          respond_with @photograph, status: :unprocessable_entity do |f|
            f.html { render :edit }
          end
        end
      end
    end

    def mass_update
      @mass_edit = MassEdit.new(params[:mass_edit])
      @mass_edit.user = current_user

      if @mass_edit.photograph_ids.size > 0
        perform_mass_update
      else
        flash[:alert] = t("account.photographs.mass_update.no_photos_selected")
      end

      respond_with @mass_edit.photographs do |f|
        f.html { redirect_to :back }
      end
    end

    def destroy
      @photograph = current_user.photographs.find(params[:id])
      authorize! :destroy, @photograph
      if @photograph.destroy
        flash[:notice] = t("account.photographs.destroy.succeeded")
        respond_with @photograph do |f|
          f.html { redirect_to account_photographs_path }
        end
      else
        flash[:alert] = t("account.photographs.destroy.failed")
        respond_with @photograph, status: :bad_request do |f|
          f.html { redirect_to :back }
        end
      end
    end

    def typeahead
      @values = Rails.cache.fetch([current_user, :typeahead, params[:key]], expires_in: 5.minutes) do
        @values = Rails.cache.fetch([current_user, :typeahead], expires_in: 10.minutes) do
          Metadata::EDITABLE_KEYS.reduce({}) do |hash, key|
            hash[key] = current_user.metadata.map do |m|
              value = m.send(key)
              { value: value, tokens: value.to_s.split(" ") }
            end
            hash[key].keep_if { |val| val[:value].present? }
            hash
          end
        end

        if params[:key].present?
          @values = @values[params[:key].to_sym]
        else
          @values
        end
      end

      respond_with @values do |f|
        f.json { render json: @values.to_json }
      end
    end
    
    private
    def upload_params
      params.permit(:file, :filepath, :unique_id, :filename, :filesize, :filetype, :url)
    end

    def photograph_params
      params.require(:photograph).permit(
        :image_uid, :safe_for_work, :show_location_data, :license_id, :category_id,
        :show_copyright_info, :enable_comments,
        collection_ids: [], metadata_attributes: Metadata::EDITABLE_KEYS,
        comment_threads_attributes: [:id, :subject, :_destroy]
      )
    end

    def perform_mass_update
      begin
        Photograph.transaction do
          case
          when @mass_edit.action == 'collections'
            @mass_edit.photographs.each do |photograph|
              perform_collection_update(photograph)
            end
          when @mass_edit.action == 'delete'
            perform_deletion
          when @mass_edit.action == 'reprocess'
            perform_reprocess
          end
        end

      rescue ActiveRecord::StatementInvalid
        flash[:notice] = t("account.photographs.mass_update.failed")
        raise ActiveRecord::Rollback
      end
    end

    def perform_collection_update(photograph)
      if @collection.present?
        # Prevent removal from other collections
        if !@mass_edit.collection_ids.include?(@collection.id)
          photograph.collection_photographs.where(collection_id: @collection.id).find_each(&:destroy)
        end
      end

      @mass_edit.collection_ids.each do |id|
        photograph.collection_photographs.find_or_create_by(collection_id: id)
      end

      flash[:notice] = t("account.photographs.mass_update.collections.succeeded")
    end

    def perform_deletion
      @mass_edit.photographs.each(&:destroy)
      flash[:notice] = t("account.photographs.mass_update.delete.succeeded")
    end

    def perform_reprocess
      @mass_edit.photographs.stuck_processing.each(&:create_sizes)
      flash[:notice] = t("account.photographs.mass_update.reprocess.succeeded")
    end
  end
end

app/helpers/photographs_helper.rb
module PhotographsHelper
  class DeprecatedPhoto < StandardError; end
  class Processing < StandardError; end

  SHORT_METADATA_KEYS = [
    :model, :lens_type, :lens_model, :aperture, :focal_length, :shutter_speed, :iso,
    :copyright_notice, :creator, :creator_country, :creator_city,
    :date_time_original
  ]

  def photo_tag(photograph, size = :thumbnail, opts = {})
    return nil if photograph.nil?

    begin
      raise DeprecatedPhoto if !photograph.has_precalculated_sizes?
      raise Processing if photograph.nil? || photograph.processing?
      
      image = case size
      when :homepage
        photograph.homepage_image
      when :large
        photograph.large_image
      when :thumbnail
        photograph.thumbnail_image
      when :small
        photograph.small_thumbnail_image
      else
        photograph.thumbnail_image
      end

      raise Processing if image.nil?
      url = image_url(image)

      if match = url.match(/\d+x\d+.jpg/i)
        width, height = match.to_a.last.split(".").first.split("x")
        image_tag url, { 
          alt: photograph.metadata.title,
          width: width,
          height: height
        }.merge(opts)
      else
        image_tag url, {
          alt: photograph.metadata.title
        }.merge(opts)
      end

    rescue Processing
      image_tag "processing_#{size.to_s}.jpg"
    rescue DeprecatedPhoto
      deprecated_photo_tag(photograph, size, opts = {})
    end
  end

  def image_url(image)
    return if image.nil?

    url = if ENV['CDN_HOST']
      image.remote_url(host: ENV['CDN_HOST'])
    else
      image.remote_url
    end

    url.gsub!(/https?:\/\//, "//")
    url.gsub!("////", "//")

    url
  end

  def hidden_image_meta_tag(image)
    url = image_url(image)
    if url.present?
      content_tag(:div, style: "display: none;", itemprop: "image") do
        url.gsub("//", "http://")
      end
    end
  end
  
  def deprecated_photo_tag(photograph, size, opts = {})
    return nil if photograph.nil?
    image = if photograph.standard_image.present?
      photograph.standard_image.thumb(size)
    else
      photograph.image.thumb(size)
    end

    image = if opts[:quality].present?
      image.encode(:jpg, "-quality #{opts[:quality]}")
    else
      image.encode(:jpg, "-quality 90")
    end

    image_tag image.url, alt: photograph.metadata.title
  end

  def creator_details_for(photograph)
    render partial: "photographs/creator", locals: {
      photograph: photograph
    }
  end

  def interactions_for(photograph)
    render partial: "photographs/interactions", locals: {
      photograph: photograph
    }
  end

  def metadata_table_for(photograph, opts = {})
    render partial: "photographs/metadata_table", locals: { 
      photograph: photograph,
      opts: opts
    }
  end

  def metadata_values_for_attr(photograph, attr, opts = {})
    attributes = photograph.metadata.send(attr)
    if opts[:format].present? && opts[:format] == :short
      attributes.keep_if do |key, value|
        SHORT_METADATA_KEYS.include?(key.to_sym)
      end
    else
      attributes
    end
  end

  def parse_and_display_metadata_value(key, value)
    begin
      case key
      when 'date_time_original'
        dt = DateTime::parse(value)
        l(dt, format: :long)
      else
        value
      end
    rescue Exception
      value
    end
  end

  def metadata_typeahead_values(attr = nil)
    @values = Rails.cache.fetch([current_user, :typeahead, attr], expires_in: 5.minutes) do
      @values = Rails.cache.fetch([current_user, :typeahead], expires_in: 10.minutes) do
        keys = Metadata::EDITABLE_KEYS.dup
        [:id, :title, :description, :keywords].each { |a| keys.delete(a) }
        keys.reduce({}) do |hash, key|
          hash[key] = current_user.metadata.map do |m|
            value = m.send(key)
            { value: value, tokens: value.to_s.split(" ") }
          end
          hash[key] = hash[key].keep_if { |val| val[:value].present? }.uniq { |val| val[:value] }
          hash
        end
      end

      if attr.present?
        @values = @values[attr.to_sym]
      else
        @values
      end
    end
  end

  def last_viewed_photograph_ids
    flash[:last_viewed_photograph_ids]
  end

  def last_viewed_photographs
    if last_viewed_photograph_ids.present?
      Photograph.view_for(current_user).where(id: flash[:last_viewed_photograph_ids])
    end
  end

  def next_photo_id(photograph, photograph_ids)
    if photograph_ids.present? && photograph_ids.size > 0
      index = photograph_ids.index(photograph.id)
      photograph_ids[(index || 0) + 1]
    end
  end

  def previous_photo_id(photograph, photograph_ids)
    if photograph_ids.present? && photograph_ids.size > 0
      index = photograph_ids.index(photograph.id)
      if index == 0
        nil
      else
        photograph_ids[(index || 0) - 1]
      end
    end
  end
end

app/views/photographs/_creator.html.slim
- user = photograph.user
aside[id="photographs-creator" itemprop="creator copyrightHolder" itemscope itemtype="http://schema.org/Person"]
  div class="row"
    div class="large-7 columns"
      - cache([I18n.locale, user, :creator_details]) do
        h4 itemprop="name"
          = user.name
        - if user.location.present?
          h5= user.location

        - if user.website_url.present?
          h6= link_to t("users.visit_site"), user.website_url, target: "_blank"

    div class="large-5 columns"
      - cache([I18n.locale, user, :avatar_and_links]) do
        - if user.avatar.present?
          div class="avatar"
            = link_to short_user_path(user.username) do
              = image_tag user.avatar.thumb("150x150#").jpg.url, alt: user.name, itemprop: "image"

        = link_to t("photographs.creator.profile"), short_user_path(user.username), class: "button tiny expand", itemprop: "url"

        = link_to t("photographs.creator.photos"), user_photographs_path(user.username), class: "button tiny success expand"

      - unless sharing_mode
        = follow_user_button(photograph.user)

app/views/photographs/_interactions.html.slim
div class="interactions"
  div class="inner"
    div class="row"
      div class="large-4 columns"
        - cache([I18n.locale, photograph, :stats], expires_in: 10.minutes) do
          div class="stats"
            span class="views" title=(t("photographs.views"))
              span class="icon"
              span class="number"
                = photograph.views.to_i

            span class="favourites" title=(t("photographs.favourites"))
              span class="icon"
              span class="number"
                = photograph.favourites_count

      div class="large-8 columns"
        - if user_signed_in? && photograph.user != current_user
          div class="actual-interactions"
            span class="recommendations"
              - if current_user.recommended?(photograph)
                a class="button small recommended success"
                  = t("photographs.recommended")
              - else
                = link_to t("photographs.recommend"), recommend_photograph_path(photograph), { method: :post, class: "button small recommend secondary", "data-remote" => true }

            span class="favourites"
              - if current_user.favourited?(photograph)
                = link_to photograph_favourite_path(photograph, current_user.favourites.where(photograph_id: photograph.id).first), method: :delete, class: "button small unfavourite alert", "data-remote" => true do
                  | &nbsp;
              - else
                = link_to photograph_favourites_path(photograph), method: :post, class: "button small favourite secondary", "data-remote" => true do
                  | &nbsp;

div class="photo-navigation"
  div class="inner"
    - previous_id = previous_photo_id(photograph, last_viewed_photograph_ids)
    - if previous_id.present?
      span class="previous"
        = link_to t("previous"), photograph_path(id: previous_id)

    - next_id = next_photo_id(photograph, last_viewed_photograph_ids)
    - if next_id.present?
      span class="next"
        = link_to t("next"), photograph_path(id: next_id)

app/views/photographs/_map.html.slim
- content_for(:stylesheets) do
  = stylesheet_link_tag "http://cdn.leafletjs.com/leaflet-0.5/leaflet.css"
  /[if lte IE 8]
    = stylesheet_link_tag "http://cdn.leafletjs.com/leaflet-0.5/leaflet.ie.css"
  
  css:
    #photograph-map {
      height: 300px;
    }

- content_for(:javascript) do
  = javascript_include_tag "http://cdn.leafletjs.com/leaflet-0.5/leaflet.js"

  javascript:
    var photoLocation = [#{photograph.metadata.lat}, #{photograph.metadata.lng}];
    var map = L.map('photograph-map').setView(photoLocation, 13);
    L.tileLayer('http://{s}.tile.cloudmade.com/#{ENV['CLOUDMADE_API_KEY']}/997/256/{z}/{x}/{y}.png', {
      attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://cloudmade.com">CloudMade</a>',
      maxZoom: 18
    }).addTo(map);
    var marker = L.marker(photoLocation).addTo(map);

div id="photograph-map"

app/views/photographs/_metadata_table.html.slim
- opts ||= {}
- cache([I18n.locale, photograph, photograph.metadata, opts], expires_in: 1.hour) do
  div class="row"
    aside class="metadata large-12 columns"
      header
        h5= t("photographs.metadata.title")
      
      table
        - sections = photograph.show_copyright_info? ? [:camera, :image, :settings, :creator] : [:camera, :image, :settings]
        - sections.each do |attr|
          - if metadata_values_for_attr(photograph, attr, opts).size > 0
            thead
              tr
                td colspan="2"
                  = t("photographs.metadata.#{attr}")
            tbody
              - metadata_values_for_attr(photograph, attr, opts).each do |key, value|
                - val = parse_and_display_metadata_value(key, value)
                - unless val.blank?
                  tr
                    td= t("photographs.metadata.#{key}")
                    td= val

        thead
          tr
            td colspan="2"
              = t("photographs.metadata.details")
        tbody
          - if photograph.category.present?
            tr
              td= t("photographs.metadata.category")
              td itemprop="genre"
                = link_to photograph.category.name, category_path(photograph.category.slug)

          tr
            td= t("photographs.metadata.license")
            td
              - if photograph.license.present?
                = photograph.license.name
              - else
                = t("photographs.metadata.default_license")

app/views/photographs/_photograph.html.slim
li[class="photo" itemprop="itemListElement" itemscope itemtype="http://schema.org/Photograph"]
  div class="wrapper"
    = link_to photograph_path(photograph), itemprop: "url" do
      - if photograph.has_precalculated_sizes?
        = photo_tag photograph, :thumbnail, itemprop: "image", width: "100%"
      - else
        = photo_tag photograph, "500x500>", quality: 70, itemprop: "image", width: "100%"
    footer class="caption" itemprop="description"
      - title = photograph.metadata.title
      = t("photographs.caption", \
          user: link_to(photograph.user.name, short_user_path(photograph.user.username)), \
          photo: link_to((title.blank? ? t("untitled") : title), photograph_path(photograph))).html_safe

app/views/photographs/index.html.slim
- content_for(:pagination) do
  - if @photographs.present? && @photographs.size > 0
    = paginate @photographs

section[id="photographs-index" itemscope itemtype="http://schema.org/ItemList"]
  - if content_for?(:title)
    == yield(:title)
  - else
    header class="row"
      div class="large-12 columns"
        h1= @title

  section class="row"
    div class="large-12 columns"
      - if @photographs.present? && @photographs.size > 0
        div class="row"
          - if hide_filters?
            div class="large-12 columns"
              == yield(:pagination)

          - else
            div class="large-3 columns"
              = render partial: "shared/filter_subnav"

            div class="large-6 columns"
              == yield(:pagination)

            div class="large-3 columns"

        div class="row"
          div class="large-12 columns"
            ul class="large-block-grid-5 small-block-grid-1 photo-grid"
              - if content_for?(:grid_block)
                == yield(:grid_block)

              = render @photographs, cache: -> (p) { [I18n.locale, p, p.user] }

        div class="row"
          div class="large-12 columns"
            == yield(:pagination)

      - else
        = t("photographs.none")

app/views/photographs/show.html.slim
- content_for(:body_extras) do
  | itemscope itemtype="http://schema.org/Photograph"

- content_for(:meta) do
  - cache([I18n.locale, @photograph, :meta]) do
    -# OpenGraph
    meta property="og:type" content="website"
    meta property="og:image" content=image_url(@photograph.large_image)
    meta property="og:image:type" content="image/jpeg"
    meta property="og:url" content=photograph_url(@photograph, host: ENV['DOMAIN'])

    - if @photograph.metadata.title.present?
      meta property="og:title" content=(@photograph.metadata.title)
    - else
      meta property="og:title" content=t("untitled")

    - if @photograph.metadata.description.present?
      meta property="og:description" content=(@photograph.metadata.description)

    -# Twitter
    meta name="twitter:card" content="photo"
    meta name="twitter:image" content=image_url(@photograph.large_image)
    meta name="twitter:url" content=photograph_url(@photograph, host: ENV['DOMAIN'])

    - if @photograph.metadata.title.present?
      meta name="twitter:title" content=(@photograph.metadata.title)
    - else
      meta name="twitter:title" content=""

    - if @photograph.metadata.description.present?
      meta name="twitter:description" content=(truncate(@photograph.metadata.description, length: 200))

section id="photographs-show"
  section class="row"
    article class="large-9 small-12 columns"
      section class="display"
        = hidden_image_meta_tag(@photograph.large_image)

        div class="image"
          - if @photograph.has_precalculated_sizes?
            = photo_tag @photograph, :large
          - else
            - if @photograph.landscape?
              = photo_tag @photograph, "1500x"
            - elsif @photograph.portrait?
              = photo_tag @photograph, "x1000"
            - else
              = photo_tag @photograph, "1500x1500>"

          - unless sharing_mode
            = interactions_for @photograph

          - cache([I18n.locale, @photograph, @photograph.metadata, :description]) do
            - if @photograph.metadata.has_text?
              aside class="description"
                h4 itemprop="name"
                  = @photograph.metadata.title

                - if @photograph.metadata.description.present?
                  div itemprop="description"
                    = md @photograph.metadata.description

              div class="clear"

        - if @photograph.comments_enabled? && !sharing_mode
          = render @photograph.comment_threads

    aside id="photographs-sidebar" class="large-3 small-12 columns"
      - unless sharing_mode
        - if user_signed_in? && current_user == @photograph.user
          = link_to t("photographs.edit"), edit_account_photograph_path(@photograph), class: "button secondary expand"

        - if user_signed_in? && current_user.moderator?
          = link_to t("reports.new.button"), new_photograph_report_path(@photograph), class: "button alert expand"

      = creator_details_for @photograph

      div class="panel share"
        h5= t("photographs.share.title")

        div class="share-url"
          label for="share-url"
            = t("photographs.share.blurb")
          input id="share-url" type="text" value=(short_photo_url(@photograph, protocol: "https"))

          - unless user_signed_in? && !current_user.show_social_buttons
            = render partial: "shared/social_buttons"

      div class="show-for-touch"
        = interactions_for @photograph
      
      - cache([I18n.locale, @photograph, @metadata, :sidebar], expires_in: 5.minutes) do
        div class="panel"
          = metadata_table_for @photograph, format: :short

        - if @photograph.collections.visible.count > 0
          div class="panel"
            h5= t("photographs.collections")
            table class="collections"
              tbody
                - @photograph.collections.visible.each do |collection|
                  tr
                    td
                      h6= link_to collection.name, collection_path(collection)
                      div class="photo-strip"
                        - collection.photographs.view_for(current_user).uniq.limit(6).each do |photo|
                          = link_to photograph_path(photo) do
                            = photo_tag photo, :small

        - if @photograph.metadata.keywords.size > 0
          div class="panel"
            h5= t("photographs.metadata.keywords")
            ul id="photographs-keywords" class="inline-list"
              - @photograph.metadata.keywords.each do |keyword|
                li
                  = link_to search_photographs_path(keyword: keyword) do
                    span class="label radius"
                      = keyword

        - if @photograph.show_location_data && @photograph.metadata.has_location_data?
          div class="panel"
            h5= t("photographs.location")
            = render partial: "map", locals: { photograph: @photograph }